export interface Skill {
  name: string;
  icon: string;
  color?: string;
  proficiency: "beginner" | "intermediate" | "advanced" | "expert";
  yearsOfExperience?: number;
  description?: string;
  isHighlighted?: boolean;
}

export interface SkillCategory {
  title: string;
  description: string;
  icon: string;
  skills: Skill[];
  priority: number;
}

export const skillCategories: SkillCategory[] = [
  {
    title: "Frontend Development",
    description: "Building responsive and interactive user interfaces",
    icon: "palette",
    priority: 1,
    skills: [
      {
        name: "React.js",
        icon: "layers",
        color: "#61DAFB",
        proficiency: "expert",
        yearsOfExperience: 4,
        description: "Modern UI development with hooks and context",
        isHighlighted: true,
      },
      {
        name: "Next.js",
        icon: "code",
        color: "white",
        proficiency: "advanced",
        yearsOfExperience: 3,
        description: "Full-stack React framework with SSR/SSG",
        isHighlighted: true,
      },
      {
        name: "TypeScript",
        icon: "type",
        color: "#3178C6",
        proficiency: "advanced",
        yearsOfExperience: 3,
        description: "Type-safe JavaScript development",
      },
      {
        name: "JavaScript",
        icon: "code",
        color: "#F7DF1E",
        proficiency: "expert",
        yearsOfExperience: 5,
        description: "Core language and modern ES6+ features",
      },
      {
        name: "Redux Toolkit",
        icon: "layers",
        color: "#764ABC",
        proficiency: "advanced",
        yearsOfExperience: 3,
        description: "Modern state management with RTK Query",
        isHighlighted: true,
      },
      {
        name: "Tailwind CSS",
        icon: "wind",
        color: "#38B2AC",
        proficiency: "advanced",
        yearsOfExperience: 3,
        description: "Utility-first CSS framework",
      },
      {
        name: "HTML5",
        icon: "globe",
        color: "#E34F26",
        proficiency: "expert",
        yearsOfExperience: 6,
        description: "Semantic markup and accessibility",
      },
      {
        name: "CSS3",
        icon: "palette",
        color: "#1572B6",
        proficiency: "advanced",
        yearsOfExperience: 5,
        description: "Modern styling with Flexbox and Grid",
      },
      {
        name: "Framer Motion",
        icon: "zap",
        color: "#0055FF",
        proficiency: "beginner",
        yearsOfExperience: 1,
        description: "Animation library for React",
      },
    ],
  },
  {
    title: "Backend Development",
    description: "Creating robust and scalable server-side applications",
    icon: "server",
    priority: 2,
    skills: [
      {
        name: "Node.js",
        icon: "server",
        color: "#339933",
        proficiency: "advanced",
        yearsOfExperience: 4,
        description: "Server-side JavaScript runtime",
        isHighlighted: true,
      },
      {
        name: "Express.js",
        icon: "code",
        color: "white",
        proficiency: "advanced",
        yearsOfExperience: 4,
        description: "Web application framework for Node.js",
      },
      {
        name: "GraphQL",
        icon: "database",
        color: "#E535AB",
        proficiency: "beginner",
        yearsOfExperience: 1,
        description: "Query language for APIs",
      },
      {
        name: "MongoDB",
        icon: "database",
        color: "#47A248",
        proficiency: "advanced",
        yearsOfExperience: 3,
        description: "NoSQL document database",
      },
      {
        name: "PostgreSQL",
        icon: "database",
        color: "#4479A1",
        proficiency: "intermediate",
        yearsOfExperience: 2,
        description: "Relational database management",
      },
      {
        name: "Firebase",
        icon: "flame",
        color: "#FFCA28",
        proficiency: "intermediate",
        yearsOfExperience: 2,
        description: "Backend-as-a-Service platform",
      },
      {
        name: "REST APIs",
        icon: "server",
        color: "#FF6B6B",
        proficiency: "advanced",
        yearsOfExperience: 4,
        description: "Designing and consuming RESTful APIs",
      },
    ],
  },
  {
    title: "Testing & Quality",
    description: "Ensuring code quality and reliability through testing",
    icon: "zap",
    priority: 3,
    skills: [
      {
        name: "Jest",
        icon: "zap",
        color: "#C21325",
        proficiency: "beginner",
        yearsOfExperience: 1,
        description: "JavaScript testing framework",
        isHighlighted: true,
      },
      {
        name: "React Testing Library",
        icon: "layers",
        color: "#E33332",
        proficiency: "beginner",
        yearsOfExperience: 1,
        description: "Testing React components",
      },
      {
        name: "Cypress",
        icon: "zap",
        color: "#17202C",
        proficiency: "beginner",
        yearsOfExperience: 1,
        description: "End-to-end testing framework",
      },
      {
        name: "ESLint",
        icon: "code",
        color: "#4B32C3",
        proficiency: "advanced",
        yearsOfExperience: 3,
        description: "Code linting and formatting",
      },
      {
        name: "Prettier",
        icon: "code",
        color: "#F7B93E",
        proficiency: "advanced",
        yearsOfExperience: 3,
        description: "Code formatter",
      },
    ],
  },
  {
    title: "DevOps & Tools",
    description: "Tools and technologies for deployment and development",
    icon: "cloud",
    priority: 4,
    skills: [
      {
        name: "Git",
        icon: "gitBranch",
        color: "#F05032",
        proficiency: "advanced",
        yearsOfExperience: 4,
        description: "Version control and collaboration",
      },
      {
        name: "GitHub",
        icon: "github",
        color: "white",
        proficiency: "advanced",
        yearsOfExperience: 4,
        description: "Code hosting and collaboration platform",
      },
      {
        name: "GitHub Actions",
        icon: "gitBranch",
        color: "#2088FF",
        proficiency: "beginner",
        yearsOfExperience: 1,
        description: "CI/CD automation",
        isHighlighted: true,
      },
      {
        name: "Docker",
        icon: "container",
        color: "#2496ED",
        proficiency: "intermediate",
        yearsOfExperience: 2,
        description: "Containerization and deployment",
      },
      {
        name: "AWS",
        icon: "cloud",
        color: "#FF9900",
        proficiency: "intermediate",
        yearsOfExperience: 2,
        description: "Cloud computing services",
      },
      {
        name: "Vercel",
        icon: "zap",
        color: "white",
        proficiency: "advanced",
        yearsOfExperience: 3,
        description: "Frontend deployment platform",
      },
      {
        name: "npm",
        icon: "package",
        color: "#CB3837",
        proficiency: "advanced",
        yearsOfExperience: 4,
        description: "Package management and scripting",
      },
      {
        name: "Webpack",
        icon: "package",
        color: "#8DD6F9",
        proficiency: "intermediate",
        yearsOfExperience: 2,
        description: "Module bundler",
      },
    ],
  },
  {
    title: "Performance & Monitoring",
    description: "Optimizing applications and monitoring performance",
    icon: "zap",
    priority: 5,
    skills: [
      {
        name: "Lighthouse",
        icon: "zap",
        color: "#F44B21",
        proficiency: "beginner",
        yearsOfExperience: 1,
        description: "Performance auditing tool",
      },
      {
        name: "Core Web Vitals",
        icon: "zap",
        color: "#4285F4",
        proficiency: "beginner",
        yearsOfExperience: 1,
        description: "Web performance metrics",
      },
      {
        name: "Sentry",
        icon: "zap",
        color: "#362D59",
        proficiency: "beginner",
        yearsOfExperience: 1,
        description: "Error monitoring and performance tracking",
      },
      {
        name: "Google Analytics",
        icon: "globe",
        color: "#F9AB00",
        proficiency: "beginner",
        yearsOfExperience: 1,
        description: "Web analytics and user tracking",
      },
    ],
  },
];
